[[c_simple]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3fbfac0ff840158dee2694b61acbc35d5d364690"
libc = "glibc"
libgfortran_version = "5.0.0"
libstdcxx_version = "3.4.26"
os = "linux"

    [[c_simple.download]]
    sha256 = "888851619b68fd2e26b8ba36675f1166744f93140c44175333504ee15dfc699e"
    url = "https://github.com/JuliaBinaryWrappers/c_simple_jll.jl/releases/download/c_simple+v1.2.3+5/c_simple.v1.2.3.x86_64-linux-gnu-libgfortran5-libstdcxx26-cxx11.tar.gz"
