[[c_simple]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8a735c74d41476e583b0813dfcd4b960988ed8e9"
libc = "glibc"
libgfortran_version = "5.0.0"
libstdcxx_version = "3.4.26"
os = "linux"

    [[c_simple.download]]
    sha256 = "ceb359a0bb6e090def610b2191beebb4fe6c4f827edc41acdffd52488e0a8cc7"
    url = "https://github.com/JuliaBinaryWrappers/c_simple_jll.jl/releases/download/c_simple+v1.2.3+0/c_simple.v1.2.3.x86_64-linux-gnu-libgfortran5-libstdcxx26-cxx11.tar.gz"
[[c_simple]]
arch = "armv7l"
git-tree-sha1 = "ace05700eafd38326cfeaeaed3b9658e225a2500"
libc = "glibc"
os = "linux"

    [[c_simple.download]]
    sha256 = "38c4685df0a3b3797daf8bc139a69a7aaebad85b854cc8776a9735d01d31f38e"
    url = "https://github.com/JuliaBinaryWrappers/c_simple_jll.jl/releases/download/c_simple+v1.2.3+0/c_simple.v1.2.3.arm-linux-gnueabihf.tar.gz"
[[c_simple]]
arch = "x86_64"
git-tree-sha1 = "564ded0c02b659f32909df0d8c4735d700de1ab1"
os = "freebsd"

    [[c_simple.download]]
    sha256 = "81775a56b49293c6ad242b3adb70946eb36839790f2d35d75275369c294e1042"
    url = "https://github.com/JuliaBinaryWrappers/c_simple_jll.jl/releases/download/c_simple+v1.2.3+0/c_simple.v1.2.3.x86_64-unknown-freebsd11.1.tar.gz"
[[c_simple]]
arch = "x86_64"
git-tree-sha1 = "9201772395ed030c3b611555468f254f82977e89"
os = "macos"

    [[c_simple.download]]
    sha256 = "81697980e6520635b3184bade31e82af447d9b7e497810da30dd42a6dbf60e01"
    url = "https://github.com/JuliaBinaryWrappers/c_simple_jll.jl/releases/download/c_simple+v1.2.3+0/c_simple.v1.2.3.x86_64-apple-darwin14.tar.gz"
[[c_simple]]
arch = "powerpc64le"
git-tree-sha1 = "5528e6f4b156210511bfddd173f1c328eacd84f4"
libc = "glibc"
os = "linux"

    [[c_simple.download]]
    sha256 = "05dd2e6ea4edcf80b5e3f63ace5d5f0c4236d6b85cf00fec198f92b47a2f339e"
    url = "https://github.com/JuliaBinaryWrappers/c_simple_jll.jl/releases/download/c_simple+v1.2.3+0/c_simple.v1.2.3.powerpc64le-linux-gnu.tar.gz"
[[c_simple]]
arch = "i686"
git-tree-sha1 = "b2a32f866906e69b2c86544cf24b4cad618e82ee"
libc = "musl"
os = "linux"

    [[c_simple.download]]
    sha256 = "0bf07260fc0564955f3b2f9003772fb3b27795d9fb576cc3b27cb728457802b2"
    url = "https://github.com/JuliaBinaryWrappers/c_simple_jll.jl/releases/download/c_simple+v1.2.3+0/c_simple.v1.2.3.i686-linux-musl.tar.gz"
[[c_simple]]
arch = "x86_64"
git-tree-sha1 = "78614d6f3bd7ba001719e2862874720442e9de50"
libc = "musl"
os = "linux"

    [[c_simple.download]]
    sha256 = "52408d0e39a7d1cd886fbcebe2316dc6182fac9ca42d74ab181f3da0cc9976bc"
    url = "https://github.com/JuliaBinaryWrappers/c_simple_jll.jl/releases/download/c_simple+v1.2.3+0/c_simple.v1.2.3.x86_64-linux-musl.tar.gz"
[[c_simple]]
arch = "i686"
git-tree-sha1 = "8f99ef9b48cfa60029a6ceea50598cec2c9333ef"
libc = "glibc"
os = "linux"

    [[c_simple.download]]
    sha256 = "273279091fffb0299affa3093a47fb03f0021b7d596c88878e637bb00ab44f75"
    url = "https://github.com/JuliaBinaryWrappers/c_simple_jll.jl/releases/download/c_simple+v1.2.3+0/c_simple.v1.2.3.i686-linux-gnu.tar.gz"
[[c_simple]]
arch = "i686"
git-tree-sha1 = "493ecda60bf0faa0fa65ba02425425499d02fcfc"
os = "windows"

    [[c_simple.download]]
    sha256 = "af2879f4f9c6af75268713ecbf64bdb2f84f717be13278491075a3be11f6752b"
    url = "https://github.com/JuliaBinaryWrappers/c_simple_jll.jl/releases/download/c_simple+v1.2.3+0/c_simple.v1.2.3.i686-w64-mingw32.tar.gz"
[[c_simple]]
arch = "x86_64"
git-tree-sha1 = "8c194112933db5c8de5fdc55483f716642b9cdaa"
libc = "glibc"
os = "linux"

    [[c_simple.download]]
    sha256 = "7c031f8f0e1a08f26745a4978e911c9b810bd18fb681da58d63726d001c85837"
    url = "https://github.com/JuliaBinaryWrappers/c_simple_jll.jl/releases/download/c_simple+v1.2.3+0/c_simple.v1.2.3.x86_64-linux-gnu.tar.gz"
[[c_simple]]
arch = "x86_64"
git-tree-sha1 = "243fc05fb891e2fd1e462128c3524a7399413fad"
os = "windows"

    [[c_simple.download]]
    sha256 = "66ef20055881bca28f0ca6ab011b7b8eb8b04dd7b5b8850e1d55f5788ea63c94"
    url = "https://github.com/JuliaBinaryWrappers/c_simple_jll.jl/releases/download/c_simple+v1.2.3+0/c_simple.v1.2.3.x86_64-w64-mingw32.tar.gz"
[[c_simple]]
arch = "aarch64"
git-tree-sha1 = "c3c87120dfc80e1d9fb72c7c0ea319dc0da303d1"
libc = "musl"
os = "linux"

    [[c_simple.download]]
    sha256 = "f7774f6a881d4684069f8472f815575e28625e303bc7ec7d92396b2347ebcc28"
    url = "https://github.com/JuliaBinaryWrappers/c_simple_jll.jl/releases/download/c_simple+v1.2.3+0/c_simple.v1.2.3.aarch64-linux-musl.tar.gz"
[[c_simple]]
arch = "aarch64"
git-tree-sha1 = "d866813b881490965aeb0514a5f60b6b5caba183"
libc = "glibc"
os = "linux"

    [[c_simple.download]]
    sha256 = "a8661d119ce250e8ee62748eb6b48c16174950e48e223d982e911a1b56082d2d"
    url = "https://github.com/JuliaBinaryWrappers/c_simple_jll.jl/releases/download/c_simple+v1.2.3+0/c_simple.v1.2.3.aarch64-linux-gnu.tar.gz"
[[c_simple]]
arch = "armv7l"
git-tree-sha1 = "b0a512cb7c6f3cef9d968df171575f54806848f0"
libc = "musl"
os = "linux"

    [[c_simple.download]]
    sha256 = "ce52bd28111baf8fd83cfdd8d1eea9ac75198c816b42c1034a49351472583de1"
    url = "https://github.com/JuliaBinaryWrappers/c_simple_jll.jl/releases/download/c_simple+v1.2.3+0/c_simple.v1.2.3.arm-linux-musleabihf.tar.gz"
