[[c_simple]]
arch = "x86_64"
git-tree-sha1 = "0ad689ea83f92f49ba3fb433305c5172533d5df1"
libc = "glibc"
os = "linux"

    [[c_simple.download]]
    sha256 = "64f37a5bd721dfdae86e2e56f87fea8e5a67d695c8fba0910f23468d380ff2a2"
    url = "https://github.com/JuliaBinaryWrappers/c_simple_jll.jl/releases/download/c_simple+v1.2.3+0/c_simple.v1.2.3.x86_64-linux-gnu.tar.gz"
[[c_simple]]
arch = "armv7l"
git-tree-sha1 = "590a840f7188cfadb3c88271798adfefd0cd93a2"
libc = "musl"
os = "linux"

    [[c_simple.download]]
    sha256 = "5e842074ee96bbe324361e43cae8a3a03a133437dbde517bd2f9f27b87e5d39f"
    url = "https://github.com/JuliaBinaryWrappers/c_simple_jll.jl/releases/download/c_simple+v1.2.3+0/c_simple.v1.2.3.arm-linux-musleabihf.tar.gz"
[[c_simple]]
arch = "i686"
git-tree-sha1 = "b48914abb7d42afba7902839b1c3f23a52249d0d"
os = "windows"

    [[c_simple.download]]
    sha256 = "df0c987b6b2b0bb3c4283d862aa3740ede0ada724a978fa90a61f481c80add94"
    url = "https://github.com/JuliaBinaryWrappers/c_simple_jll.jl/releases/download/c_simple+v1.2.3+0/c_simple.v1.2.3.i686-w64-mingw32.tar.gz"
[[c_simple]]
arch = "i686"
git-tree-sha1 = "0540e576bd9b75107bbdddb24d43d6ca86ac0259"
libc = "glibc"
os = "linux"

    [[c_simple.download]]
    sha256 = "5f2ae050eed32aa663ee8e21ba8591e46dfe142d4666dc916db3c7481ddc0064"
    url = "https://github.com/JuliaBinaryWrappers/c_simple_jll.jl/releases/download/c_simple+v1.2.3+0/c_simple.v1.2.3.i686-linux-gnu.tar.gz"
[[c_simple]]
arch = "x86_64"
git-tree-sha1 = "2fc73bbbb20d5b75b7efb19b70e067cd3aef6b83"
libc = "musl"
os = "linux"

    [[c_simple.download]]
    sha256 = "ad1d2fe614e52ca5824d6e26fc57b8adb331b2228f3725c5c4a50d4d22eb2946"
    url = "https://github.com/JuliaBinaryWrappers/c_simple_jll.jl/releases/download/c_simple+v1.2.3+0/c_simple.v1.2.3.x86_64-linux-musl.tar.gz"
[[c_simple]]
arch = "aarch64"
git-tree-sha1 = "e34382372aa587a6e3c1b3d978495a826aded488"
libc = "glibc"
os = "linux"

    [[c_simple.download]]
    sha256 = "8db16b5c606d869893f8459350fd43e93fb1a75ffbdac5f216c7ca1d7a075dd6"
    url = "https://github.com/JuliaBinaryWrappers/c_simple_jll.jl/releases/download/c_simple+v1.2.3+0/c_simple.v1.2.3.aarch64-linux-gnu.tar.gz"
[[c_simple]]
arch = "aarch64"
git-tree-sha1 = "224b371126952975fc43d79715e7af325fd4d218"
libc = "musl"
os = "linux"

    [[c_simple.download]]
    sha256 = "c808892e805809ca102ceb0564576074fd5098336d62abbcc475ce6542a35aeb"
    url = "https://github.com/JuliaBinaryWrappers/c_simple_jll.jl/releases/download/c_simple+v1.2.3+0/c_simple.v1.2.3.aarch64-linux-musl.tar.gz"
[[c_simple]]
arch = "armv7l"
git-tree-sha1 = "aba3b0a561392b4696bb0a1dc5e349d1ed8fa8cf"
libc = "glibc"
os = "linux"

    [[c_simple.download]]
    sha256 = "16c6292dde6bb1b0c131c2f343772c5a78722daf1723d36449e86f7bcf2bdc55"
    url = "https://github.com/JuliaBinaryWrappers/c_simple_jll.jl/releases/download/c_simple+v1.2.3+0/c_simple.v1.2.3.arm-linux-gnueabihf.tar.gz"
[[c_simple]]
arch = "x86_64"
git-tree-sha1 = "0f8b8af5fdc00982e1f3ae1247031048a544e355"
os = "windows"

    [[c_simple.download]]
    sha256 = "e7ce8bb94e3628a53ba6b14ff7ed38043231c5f1b4aaf0215b820cb5fb7c3955"
    url = "https://github.com/JuliaBinaryWrappers/c_simple_jll.jl/releases/download/c_simple+v1.2.3+0/c_simple.v1.2.3.x86_64-w64-mingw32.tar.gz"
[[c_simple]]
arch = "powerpc64le"
git-tree-sha1 = "531a1a490955c71db16f45e28f928671b7b2128e"
libc = "glibc"
os = "linux"

    [[c_simple.download]]
    sha256 = "d79ff08ef53ca40a046b5aafd70bbc6249e91b9a12e1421fa9ab2f148d6a9306"
    url = "https://github.com/JuliaBinaryWrappers/c_simple_jll.jl/releases/download/c_simple+v1.2.3+0/c_simple.v1.2.3.powerpc64le-linux-gnu.tar.gz"
[[c_simple]]
arch = "x86_64"
git-tree-sha1 = "c7554d9325374dbb9f62ea07331c64612d9c57fd"
os = "macos"

    [[c_simple.download]]
    sha256 = "0dc6e97cd736442f58f3e5bf31f6e2308248de10923c71560d6b4439f00a57e7"
    url = "https://github.com/JuliaBinaryWrappers/c_simple_jll.jl/releases/download/c_simple+v1.2.3+0/c_simple.v1.2.3.x86_64-apple-darwin14.tar.gz"
[[c_simple]]
arch = "x86_64"
git-tree-sha1 = "9ff5477c404e1195278b78d9f28e455cbc0f1d62"
os = "freebsd"

    [[c_simple.download]]
    sha256 = "16d8b9d3108fcb31e693a58ef3d4ff3f508cdd5a44ccbf39b6c7f209806c6bde"
    url = "https://github.com/JuliaBinaryWrappers/c_simple_jll.jl/releases/download/c_simple+v1.2.3+0/c_simple.v1.2.3.x86_64-unknown-freebsd11.1.tar.gz"
[[c_simple]]
arch = "i686"
git-tree-sha1 = "15220a8b637fe63f6fae969691fb83ad1f0cdb01"
libc = "musl"
os = "linux"

    [[c_simple.download]]
    sha256 = "1fdbc48ce22ca21907261a8daa730cae2e6dc6e9c41abcd4ea725ec0ab966e77"
    url = "https://github.com/JuliaBinaryWrappers/c_simple_jll.jl/releases/download/c_simple+v1.2.3+0/c_simple.v1.2.3.i686-linux-musl.tar.gz"
[[c_simple]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8d5eb8aa98a9ffcafcab3369efbb64d0b141c15b"
libc = "glibc"
libgfortran_version = "5.0.0"
libstdcxx_version = "3.4.26"
os = "linux"

    [[c_simple.download]]
    sha256 = "37c669330d578c7d070e0e35da1ebc8807844c7400dfe79aba2c2b3fee6e4eb1"
    url = "https://github.com/JuliaBinaryWrappers/c_simple_jll.jl/releases/download/c_simple+v1.2.3+0/c_simple.v1.2.3.x86_64-linux-gnu-libgfortran5-libstdcxx26-cxx11.tar.gz"
