[[c_simple]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "47b821dcd4a2fa4e8896a21644cd3445e2da85f3"
libc = "glibc"
libgfortran_version = "5.0.0"
libstdcxx_version = "3.4.26"
os = "linux"

    [[c_simple.download]]
    sha256 = "c0da8944427a87cd4a8cf7273b76e1d17d737d087cb7b24f4b4a7da027f8171b"
    url = "https://github.com/JuliaBinaryWrappers/c_simple_jll.jl/releases/download/c_simple+v1.2.3+0/c_simple.v1.2.3.x86_64-linux-gnu-libgfortran5-libstdcxx26-cxx11.tar.gz"
[[c_simple]]
arch = "i686"
git-tree-sha1 = "315e9d5f5ed3990c7cd670ec30bbf386543b2239"
libc = "musl"
os = "linux"

    [[c_simple.download]]
    sha256 = "9a4355476bd21cbeb62410dfec9a99ef68b2d1afcbd5334438b35ff101b5a2db"
    url = "https://github.com/JuliaBinaryWrappers/c_simple_jll.jl/releases/download/c_simple+v1.2.3+2/c_simple.v1.2.3.i686-linux-musl.tar.gz"
[[c_simple]]
arch = "x86_64"
git-tree-sha1 = "a7f766886feac41d560c850d94adf9e1006ae15a"
libc = "glibc"
os = "linux"

    [[c_simple.download]]
    sha256 = "0fa36f1f424763c90a7701fdab2810ac5165e610a7ebfbad1b0f4d2bb49e4d1a"
    url = "https://github.com/JuliaBinaryWrappers/c_simple_jll.jl/releases/download/c_simple+v1.2.3+2/c_simple.v1.2.3.x86_64-linux-gnu.tar.gz"
[[c_simple]]
arch = "x86_64"
git-tree-sha1 = "1ce4aa1665a20f202613f036031f3fec1ac9abcc"
os = "freebsd"

    [[c_simple.download]]
    sha256 = "29d03f4d718931d951bfd00b71492e7df840b0716f37a80b76106fe3fac5470f"
    url = "https://github.com/JuliaBinaryWrappers/c_simple_jll.jl/releases/download/c_simple+v1.2.3+2/c_simple.v1.2.3.x86_64-unknown-freebsd11.1.tar.gz"
[[c_simple]]
arch = "aarch64"
git-tree-sha1 = "88842d65ab5bc343322d578af3e39ec6b52fd155"
libc = "glibc"
os = "linux"

    [[c_simple.download]]
    sha256 = "a54091ef91463dd7877e6ac36d514353667f9a03d77f4adb3b8d2e004c6c67dd"
    url = "https://github.com/JuliaBinaryWrappers/c_simple_jll.jl/releases/download/c_simple+v1.2.3+2/c_simple.v1.2.3.aarch64-linux-gnu.tar.gz"
[[c_simple]]
arch = "i686"
git-tree-sha1 = "d6e410c3db445855f49050239bcfb4a28d578e97"
libc = "glibc"
os = "linux"

    [[c_simple.download]]
    sha256 = "9e26c500eda8dbe62e11e9a59d152f41f81575027d5d82d8d2b7e698d2970a1e"
    url = "https://github.com/JuliaBinaryWrappers/c_simple_jll.jl/releases/download/c_simple+v1.2.3+2/c_simple.v1.2.3.i686-linux-gnu.tar.gz"
[[c_simple]]
arch = "x86_64"
git-tree-sha1 = "499ae95ec0d0aedd8b2049fcda50aebf76fb812c"
os = "windows"

    [[c_simple.download]]
    sha256 = "b22b44f7e56ea7f28fb4f9a9ac5be5c8652dd2bf2048c48b99df01df471b4951"
    url = "https://github.com/JuliaBinaryWrappers/c_simple_jll.jl/releases/download/c_simple+v1.2.3+2/c_simple.v1.2.3.x86_64-w64-mingw32.tar.gz"
[[c_simple]]
arch = "x86_64"
git-tree-sha1 = "ad48421a03629502cc9ffee47247c96522b6393f"
os = "macos"

    [[c_simple.download]]
    sha256 = "0a0d17a4cd1f6754e1ffff8cb3bb7034b6c8b34691a6a000a61d8e85abf5611c"
    url = "https://github.com/JuliaBinaryWrappers/c_simple_jll.jl/releases/download/c_simple+v1.2.3+2/c_simple.v1.2.3.x86_64-apple-darwin14.tar.gz"
[[c_simple]]
arch = "x86_64"
git-tree-sha1 = "bd702fc1098b2a224483ab1e6e734bfb74397633"
libc = "musl"
os = "linux"

    [[c_simple.download]]
    sha256 = "2845de11be1c5231d1508c5a5f97d013e3ef6c35b9da020f380781672abce2f5"
    url = "https://github.com/JuliaBinaryWrappers/c_simple_jll.jl/releases/download/c_simple+v1.2.3+2/c_simple.v1.2.3.x86_64-linux-musl.tar.gz"
[[c_simple]]
arch = "i686"
git-tree-sha1 = "7c9a4db77be3099ed2a7ffad657997d320d7f37a"
os = "windows"

    [[c_simple.download]]
    sha256 = "eb28e334b5d3a18345bd92ec0afe29c408d9f3f0f6162845b5b0380f0d147186"
    url = "https://github.com/JuliaBinaryWrappers/c_simple_jll.jl/releases/download/c_simple+v1.2.3+2/c_simple.v1.2.3.i686-w64-mingw32.tar.gz"
[[c_simple]]
arch = "armv7l"
git-tree-sha1 = "6ed46e7f82a1ae1319a932d9c98ddef5066a8136"
libc = "glibc"
os = "linux"

    [[c_simple.download]]
    sha256 = "fc3a8052139cce4dae78d665e72913fbc146c09a422d16202f71b8535e7ecaaf"
    url = "https://github.com/JuliaBinaryWrappers/c_simple_jll.jl/releases/download/c_simple+v1.2.3+2/c_simple.v1.2.3.arm-linux-gnueabihf.tar.gz"
[[c_simple]]
arch = "powerpc64le"
git-tree-sha1 = "7ca5e5ec7fb674ec9ac07fb338840f61d2ba22bf"
libc = "glibc"
os = "linux"

    [[c_simple.download]]
    sha256 = "a381014acf9f6a0fce34b2dd7189eca72ea25a580c1231802f381abf16dba9fa"
    url = "https://github.com/JuliaBinaryWrappers/c_simple_jll.jl/releases/download/c_simple+v1.2.3+2/c_simple.v1.2.3.powerpc64le-linux-gnu.tar.gz"
[[c_simple]]
arch = "aarch64"
git-tree-sha1 = "a23507ffee47d0669da17b836b5ec17e8ca2ba05"
libc = "musl"
os = "linux"

    [[c_simple.download]]
    sha256 = "8812687f4a9d23fd4e3af5d0fc2833f54e3ab621e1080a4c170c4185b872c589"
    url = "https://github.com/JuliaBinaryWrappers/c_simple_jll.jl/releases/download/c_simple+v1.2.3+2/c_simple.v1.2.3.aarch64-linux-musl.tar.gz"
[[c_simple]]
arch = "armv7l"
git-tree-sha1 = "3701de66be1a93e84974b888466d9e92e17f2ed4"
libc = "musl"
os = "linux"

    [[c_simple.download]]
    sha256 = "82f45fa38461ecf3431ab1b96fcac6722085201958b740cd86d70334ef113555"
    url = "https://github.com/JuliaBinaryWrappers/c_simple_jll.jl/releases/download/c_simple+v1.2.3+2/c_simple.v1.2.3.arm-linux-musleabihf.tar.gz"
