[[c_simple]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8a735c74d41476e583b0813dfcd4b960988ed8e9"
libc = "glibc"
libgfortran_version = "5.0.0"
libstdcxx_version = "3.4.26"
os = "linux"

    [[c_simple.download]]
    sha256 = "ceb359a0bb6e090def610b2191beebb4fe6c4f827edc41acdffd52488e0a8cc7"
    url = "https://github.com/JuliaBinaryWrappers/c_simple_jll.jl/releases/download/c_simple+v1.2.3+0/c_simple.v1.2.3.x86_64-linux-gnu-libgfortran5-libstdcxx26-cxx11.tar.gz"
[[c_simple]]
arch = "i686"
git-tree-sha1 = "8e79bfad0d15579d327258d50ceb4f05be379ab0"
libc = "glibc"
os = "linux"

    [[c_simple.download]]
    sha256 = "81adad2703d2403205bc281048ae6cb7769831370adb88eae5e3bcca7acb8a8b"
    url = "https://github.com/JuliaBinaryWrappers/c_simple_jll.jl/releases/download/c_simple+v1.2.3+0/c_simple.v1.2.3.i686-linux-gnu.tar.gz"
[[c_simple]]
arch = "powerpc64le"
git-tree-sha1 = "628a404c8463837781d9621506f857f6c4922975"
libc = "glibc"
os = "linux"

    [[c_simple.download]]
    sha256 = "34b47e4e518806cc36f7de9ec4fef8eba3221d0f290575af6c687d038667e55d"
    url = "https://github.com/JuliaBinaryWrappers/c_simple_jll.jl/releases/download/c_simple+v1.2.3+0/c_simple.v1.2.3.powerpc64le-linux-gnu.tar.gz"
[[c_simple]]
arch = "i686"
git-tree-sha1 = "2f92001fef74c45b2fb6acf66650a27167c08eb4"
libc = "musl"
os = "linux"

    [[c_simple.download]]
    sha256 = "3a7a719eda1bce761abff39a8fe6034f688e57c0b0823937cc7401cbe0c10eab"
    url = "https://github.com/JuliaBinaryWrappers/c_simple_jll.jl/releases/download/c_simple+v1.2.3+0/c_simple.v1.2.3.i686-linux-musl.tar.gz"
[[c_simple]]
arch = "i686"
git-tree-sha1 = "acb77a24ef49d7af8cdb91e96e65ab79c6eb6de8"
os = "windows"

    [[c_simple.download]]
    sha256 = "7521c7d91b7266092fcba39147f0d21002cabcb798a963f25221736f91adf4ed"
    url = "https://github.com/JuliaBinaryWrappers/c_simple_jll.jl/releases/download/c_simple+v1.2.3+0/c_simple.v1.2.3.i686-w64-mingw32.tar.gz"
[[c_simple]]
arch = "aarch64"
git-tree-sha1 = "a09d2cc88c1baa599a2fa206f9ac3255a69f6e7c"
libc = "musl"
os = "linux"

    [[c_simple.download]]
    sha256 = "87f99d77fcf17a248604d4a2b99c8107af7a3140c247f732d958edbf771857a3"
    url = "https://github.com/JuliaBinaryWrappers/c_simple_jll.jl/releases/download/c_simple+v1.2.3+0/c_simple.v1.2.3.aarch64-linux-musl.tar.gz"
[[c_simple]]
arch = "x86_64"
git-tree-sha1 = "fe9e82c3d20683cf930e8a128ae509016067754f"
os = "macos"

    [[c_simple.download]]
    sha256 = "e764158e7c29c1171e3c4103a265b16d1c4702b09955fe392e2c7769741d2561"
    url = "https://github.com/JuliaBinaryWrappers/c_simple_jll.jl/releases/download/c_simple+v1.2.3+0/c_simple.v1.2.3.x86_64-apple-darwin14.tar.gz"
[[c_simple]]
arch = "x86_64"
git-tree-sha1 = "6f750482522e360c0735388b498a464b3bcee8d0"
os = "windows"

    [[c_simple.download]]
    sha256 = "c43cede36078903d2cbc72f1cf5b3307c2d1cadffe10e189867d751a2e013167"
    url = "https://github.com/JuliaBinaryWrappers/c_simple_jll.jl/releases/download/c_simple+v1.2.3+0/c_simple.v1.2.3.x86_64-w64-mingw32.tar.gz"
[[c_simple]]
arch = "armv7l"
git-tree-sha1 = "421dd0eb568e7d2c351ce4e6f23f9b4f3081d33a"
libc = "glibc"
os = "linux"

    [[c_simple.download]]
    sha256 = "c2a208b0c6c611aec258273c7e66968aa924ceb9fb58e21e133e66e192c93e72"
    url = "https://github.com/JuliaBinaryWrappers/c_simple_jll.jl/releases/download/c_simple+v1.2.3+0/c_simple.v1.2.3.arm-linux-gnueabihf.tar.gz"
[[c_simple]]
arch = "x86_64"
git-tree-sha1 = "e6ccdfbb50a31ee4726d09504b2ade050516b684"
libc = "glibc"
os = "linux"

    [[c_simple.download]]
    sha256 = "1e27795d3fc12379faa3813d58242ec5a072311524908284b62b7e22a0874390"
    url = "https://github.com/JuliaBinaryWrappers/c_simple_jll.jl/releases/download/c_simple+v1.2.3+0/c_simple.v1.2.3.x86_64-linux-gnu.tar.gz"
[[c_simple]]
arch = "x86_64"
git-tree-sha1 = "9da5ee595b419e5083104d110e5aa1279ac955cf"
os = "freebsd"

    [[c_simple.download]]
    sha256 = "041f31b628e9b90bbc544610674b2ba50af56d3bfb308178790ea6bd5e8bd144"
    url = "https://github.com/JuliaBinaryWrappers/c_simple_jll.jl/releases/download/c_simple+v1.2.3+0/c_simple.v1.2.3.x86_64-unknown-freebsd11.1.tar.gz"
[[c_simple]]
arch = "aarch64"
git-tree-sha1 = "6fb7ec4d9fdf239d119558eb91fa73091b789eed"
libc = "glibc"
os = "linux"

    [[c_simple.download]]
    sha256 = "e38d26a91a17c1e16dd634d525b817b5a2d8c5145b7b00ba82648b7c59791eef"
    url = "https://github.com/JuliaBinaryWrappers/c_simple_jll.jl/releases/download/c_simple+v1.2.3+0/c_simple.v1.2.3.aarch64-linux-gnu.tar.gz"
[[c_simple]]
arch = "armv7l"
git-tree-sha1 = "8cce54c118336cce0982a9a588920912fd60ebdc"
libc = "musl"
os = "linux"

    [[c_simple.download]]
    sha256 = "de4941ca602205efc19e75879629106105b87344ee19ad17e6a57a50dd456a7c"
    url = "https://github.com/JuliaBinaryWrappers/c_simple_jll.jl/releases/download/c_simple+v1.2.3+0/c_simple.v1.2.3.arm-linux-musleabihf.tar.gz"
[[c_simple]]
arch = "x86_64"
git-tree-sha1 = "8e13f24d73bb251eb8872d1eb1f7d78370670a06"
libc = "musl"
os = "linux"

    [[c_simple.download]]
    sha256 = "90c8dc6652bbf4ac988e0910209af2912b51bd33c71e15a7976374cdf3ea0860"
    url = "https://github.com/JuliaBinaryWrappers/c_simple_jll.jl/releases/download/c_simple+v1.2.3+0/c_simple.v1.2.3.x86_64-linux-musl.tar.gz"
